# Generated by Django 3.2.7 on 2021-10-08 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('commodity', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CommodityRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institution.commodity')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('headquarters', models.TextField()),
                ('region', models.TextField()),
                ('ceo_name', models.TextField()),
                ('commodities', models.ManyToManyField(through='institution.CommodityRel', to='institution.Commodity')),
            ],
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('headquarters', models.TextField()),
                ('region', models.TextField()),
                ('ceo_name', models.TextField()),
                ('commodities', models.ManyToManyField(through='institution.CommodityRel', to='institution.Commodity')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialType',
            fields=[
                ('type', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Handle',
            fields=[
                ('handle', models.TextField(primary_key=True, serialize=False)),
                ('id', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='twitter.user')),
            ],
        ),
        migrations.CreateModel(
            name='HandleRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('list', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='institution.company')),
                ('financial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='institution.financial')),
                ('handle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institution.handle')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('text', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('text', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Signatory',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institution.company')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institution.segment')),
            ],
        ),
        migrations.CreateModel(
            name='Journalist',
            fields=[
                ('contact_name', models.TextField(primary_key=True, serialize=False)),
                ('outlet_name', models.TextField()),
                ('contact_title', models.TextField()),
                ('contact_city', models.TextField()),
                ('contact_country', models.TextField()),
                ('cision_contact', models.BooleanField()),
                ('contact_subjects', models.ManyToManyField(to='institution.Subject')),
                ('handle', models.ManyToManyField(through='institution.HandleRel', to='institution.Handle')),
            ],
        ),
        migrations.AddField(
            model_name='handlerel',
            name='journalist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='institution.journalist'),
        ),
        migrations.AddField(
            model_name='financial',
            name='financial_types',
            field=models.ManyToManyField(to='institution.FinancialType'),
        ),
        migrations.AddField(
            model_name='financial',
            name='handles',
            field=models.ManyToManyField(through='institution.HandleRel', to='institution.Handle'),
        ),
        migrations.AddField(
            model_name='financial',
            name='signatories',
            field=models.ManyToManyField(to='institution.Signatory'),
        ),
        migrations.AddField(
            model_name='company',
            name='handles',
            field=models.ManyToManyField(through='institution.HandleRel', to='institution.Handle'),
        ),
        migrations.AddField(
            model_name='company',
            name='sectors',
            field=models.ManyToManyField(to='institution.Sector'),
        ),
        migrations.AddField(
            model_name='company',
            name='segments',
            field=models.ManyToManyField(through='institution.SegmentRel', to='institution.Segment'),
        ),
        migrations.AddField(
            model_name='company',
            name='signatories',
            field=models.ManyToManyField(to='institution.Signatory'),
        ),
        migrations.AddField(
            model_name='commodityrel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='institution.company'),
        ),
        migrations.AddField(
            model_name='commodityrel',
            name='financial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='institution.financial'),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institution.company')),
            ],
        ),
    ]
