# Generated by Django 3.2.7 on 2021-10-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('status', models.ManyToManyField(to='twitter.Status')),
            ],
        ),
    ]
